language: php

php:
- 7.1.9

services:
- mysql

before_script:
- cd soen341-UB3-QA
- mysql -e 'CREATE DATABASE IF NOT EXISTS projectub3;'
- composer install --no-interaction
- composer self-update
- php artisan key:generate
- php artisan migrate --no-interaction -vvv

script:
- vendor/bin/phpunit
